a = 'Hello world!'.startswith('Hello')
print(a)
b = 'Hello world!'.endswith('world!')
print(b)
c = 'abc123'.startswith('abcdef')
print(c)
d = 'abc123'.endswith('12')
print(d)
e = 'Hello world!'.startswith('Hello world!')
print(e)
f = 'Hello world!'.endswith('Hello world!')
print(f)

g = 'Hello'.rjust(10)
print(g)
h = 'Hello'.rjust(20)
print(h)
i = 'Hello World'.rjust(20)
print(i)
j = 'Hello'.ljust(10)
print(j)
k = 'Hello'.rjust(20, '*')
print(k)
l = 'Hello'.ljust(20, '-')
print(l)
m = 'Hello'.center(20)
print(m)
n = 'Hello'.center(20, '=')
print(n)